openapi: 3.0.0
servers: []
info:
  description: Permite crear, consultar y listar a las personas.
  version: "1.0.0"
  title: Persons V1
  contact:
    email: joselopez11c@gmail.com
tags:
  - name: Person
    description: Person Controller
paths:
  /creacliente:
    post:
      tags:
        - Person
      summary: Crea personas.
      operationId: createPerson
      description: |
        Endpoint que permite crear personas.
      requestBody:
        description: Entrada del Servicio.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonCreateRequest'
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/PersonCreateRequest'
      responses:
        '201':
          description: Se creó la persona.
        '400':
          description: Error en Request.
        '500':
          description: Error en el servidor.
  /kpideclientes:
    get:
      tags:
        - Person
      summary: Promedio de edad entre todos los clientes.
      operationId: searchKpiPerson
      description: |
        Promedio de edad entre todos los clientes.
      responses:
        '200':
          description: Promedio de edad entre todos los clientes.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonKpiResponse'
        '400':
          description: Error en Request.
        '500':
          description: Error en el servidor.
  /listclientes:
    get:
      tags:
        - Person
      summary: Lista de personas
      operationId: searchListClient
      description: |
        Lista de personas con todos los datos con su fecha probable de muerte de cada una.
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonResponse'
        '400':
          description: Error en Request.
        '500':
          description: Error en el servidor.
components:
  schemas:
    PersonCreateRequest:
      title: PersonCreateRequest
      required:
        - name
        - lastName
        - age
      type: object
      properties:
        name:
          type: string
          description: Nombres
          maxLength: 50
          minLength: 1
          example: Juan Carlos
        lastName:
          type: string
          description: Apellidos
          maxLength: 50
          minLength: 1
          example: Lopez Cure
        age:
          type: string
          description: Edad
          maxLength: 2
          minLength: 1
          example: 28
        birthDate:
          type: string
          format: date
          description: Fecha de nacimiento
          example: "2021-01-30"
    PersonKpiResponse:
      title: PersonKpiResponse
      type: object
      properties:
        averageAge:
          type: number
          example: 26
        standardDeviation:
          type: number
          example: 1.5
    PersonResponse:
      title: PersonResponse
      type: object
      properties:
        name:
          type: string
          description: Nombres
          maxLength: 50
          minLength: 1
          example: Juan Carlos
        lastName:
          type: string
          description: Apellidos
          maxLength: 50
          minLength: 1
          example: Lopez Cure
        age:
          type: string
          description: Edad
          maxLength: 2
          minLength: 1
          example: 28
        birthDate:
          type: string
          format: date
          description: Fecha de nacimiento
          example: "2021-01-30"
        probableDateDeath:
          type: string
          format: date
          description: Fecha probable de muerte
          example: "2021-01-30"